"""Thin stub for the h3 v4 surface FableWorldSim calls (upstream untyped).

Deliberately explicit — no module __getattr__ — so mypy flags any call
outside the vetted surface. Extend when the adapter grows.
"""

class H3NotNeighborsError(ValueError): ...

def get_res0_cells() -> list[str]: ...
def get_num_cells(res: int) -> int: ...
def cell_to_children(cell: str, res: int) -> list[str]: ...
def cell_to_parent(cell: str, res: int) -> str: ...
def grid_disk(cell: str, k: int) -> list[str]: ...
def cell_area(cell: str, unit: str = ...) -> float: ...
def cell_to_latlng(cell: str) -> tuple[float, float]: ...
def latlng_to_cell(lat: float, lng: float, res: int) -> str: ...
def cells_to_directed_edge(origin: str, destination: str) -> str: ...
def edge_length(edge: str, unit: str = ...) -> float: ...
