"""Thin stub for the s2sphere surface FableWorldSim calls.

Upstream is unmaintained (archived 2023) and untyped; this covers only
the vetted call surface so mypy flags anything outside it.
"""

from collections.abc import Iterator
from typing import Any

class Point:
    def angle(self, other: Point) -> float: ...

class LatLng:
    @staticmethod
    def from_degrees(lat: float, lng: float) -> LatLng: ...
    @staticmethod
    def from_point(point: Point) -> LatLng: ...
    def lat(self) -> Any: ...
    def lng(self) -> Any: ...

class CellId:
    @staticmethod
    def begin(level: int) -> CellId: ...
    @staticmethod
    def end(level: int) -> CellId: ...
    @staticmethod
    def from_token(token: str) -> CellId: ...
    @staticmethod
    def from_lat_lng(latlng: LatLng) -> CellId: ...
    def to_token(self) -> str: ...
    def next(self) -> CellId: ...
    def parent(self, level: int) -> CellId: ...
    def children(self) -> Iterator[CellId]: ...
    def get_edge_neighbors(self) -> list[CellId]: ...
    def to_lat_lng(self) -> LatLng: ...
    def level(self) -> int: ...

class Cell:
    def __init__(self, cell_id: CellId) -> None: ...
    def get_vertex(self, k: int) -> Point: ...
    def exact_area(self) -> float: ...
