"""Thin stub for the shapely.geometry surface FableWorldSim calls.

Only the geometry operations the ISEA adapter touches (polygon area
input, centroid, boundary intersection, adjacency tests); upstream ships
no type information of its own.
"""

from collections.abc import Sequence

class BaseGeometry:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def centroid(self) -> BaseGeometry: ...
    @property
    def exterior(self) -> BaseGeometry: ...
    @property
    def coords(self) -> Sequence[tuple[float, float]]: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def length(self) -> float: ...
    @property
    def geom_type(self) -> str: ...
    @property
    def geoms(self) -> Sequence[BaseGeometry]: ...
    def touches(self, other: BaseGeometry) -> bool: ...
    def contains(self, other: BaseGeometry) -> bool: ...
    def intersection(self, other: BaseGeometry) -> BaseGeometry: ...
    def buffer(self, distance: float) -> BaseGeometry: ...

class Point(BaseGeometry):
    def __init__(self, x: float, y: float) -> None: ...

class Polygon(BaseGeometry): ...
