"""Thin stub for the fluent.runtime surface FableWorldSim calls."""

from collections.abc import Mapping, Sequence
from typing import Any

class FluentResource:
    def __init__(self, source: str) -> None: ...

class FluentBundle:
    def __init__(self, locales: Sequence[str], *, use_isolating: bool = ...) -> None: ...
    def add_resource(self, resource: FluentResource) -> None: ...
    def has_message(self, message_id: str) -> bool: ...
    def get_message(self, message_id: str) -> Any: ...
    def format_pattern(
        self, pattern: Any, args: Mapping[str, Any] | None = ...
    ) -> tuple[Any, list[Any]]: ...
